// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4OKOyxkac53gVk2XJnR3lb7mv_I6Zx2c',
    appId: '1:638227129372:web:7a354ce6795a09b1646bd9',
    messagingSenderId: '638227129372',
    projectId: 'city-guide-app-2e1a3',
    authDomain: 'city-guide-app-2e1a3.firebaseapp.com',
    storageBucket: 'city-guide-app-2e1a3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuuz9Wy5P7bKy1HeJmwp-RKHpi6QLq0KY',
    appId: '1:638227129372:android:f8db3eacb2433a65646bd9',
    messagingSenderId: '638227129372',
    projectId: 'city-guide-app-2e1a3',
    storageBucket: 'city-guide-app-2e1a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmdhKwaICD9z2G7BVaeYECrbUCJ1_YRkM',
    appId: '1:638227129372:ios:22aaaa08ca99138b646bd9',
    messagingSenderId: '638227129372',
    projectId: 'city-guide-app-2e1a3',
    storageBucket: 'city-guide-app-2e1a3.firebasestorage.app',
    iosBundleId: 'com.example.cityGuide',
  );
}
