// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF3TgqIEI9YejAh42E6cHxK0wEywrT7Aw',
    appId: '1:990990112982:web:3b00e4f70341464dd09177',
    messagingSenderId: '990990112982',
    projectId: 'tripbudget-a6643',
    authDomain: 'tripbudget-a6643.firebaseapp.com',
    storageBucket: 'tripbudget-a6643.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO5Q70-QLmh_tASO-s1EX80nJuL6iO7qw',
    appId: '1:990990112982:android:e64019ac188785e7d09177',
    messagingSenderId: '990990112982',
    projectId: 'tripbudget-a6643',
    storageBucket: 'tripbudget-a6643.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOvFDoZmXMTUQC7_eVIctyLV0g_AGGH04',
    appId: '1:990990112982:ios:768f1dd549b07a96d09177',
    messagingSenderId: '990990112982',
    projectId: 'tripbudget-a6643',
    storageBucket: 'tripbudget-a6643.firebasestorage.app',
    iosBundleId: 'com.example.tripbudget',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOvFDoZmXMTUQC7_eVIctyLV0g_AGGH04',
    appId: '1:990990112982:ios:768f1dd549b07a96d09177',
    messagingSenderId: '990990112982',
    projectId: 'tripbudget-a6643',
    storageBucket: 'tripbudget-a6643.firebasestorage.app',
    iosBundleId: 'com.example.tripbudget',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF3TgqIEI9YejAh42E6cHxK0wEywrT7Aw',
    appId: '1:990990112982:web:026ee33e5b095ecbd09177',
    messagingSenderId: '990990112982',
    projectId: 'tripbudget-a6643',
    authDomain: 'tripbudget-a6643.firebaseapp.com',
    storageBucket: 'tripbudget-a6643.firebasestorage.app',
  );

}